spring:
datasource:
    url: jdbc:h2:mem:testdb; DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

jpa:
   hibernate:
    ddl-auto: update
   show-sql: true
   
h2:
    console:
     enabled: true
     path: /h2-console
     
# JWT Configuration
jwt:
  secret: "change-me-please-change-me-please-change-me-please" # >= 32 characters recommended
  expiration:  60 # Token expiration time in seconds
  access-exp-minutes: 2
  refresh-exp-days: 7
  
security:
  cookies:
    domain: "localhost"
    secure: false     #set true on HTTPS
    same-site: "Lax"